### ISSUE TITLE
WO SICHERUNGSUPLOAD?

### ISSUE THREAD

**Issue by renepanke** [crisstels/ChatApp#1]
![image](https://user-images.githubusercontent.com/58707844/135586081-4873aa13-bc60-463b-bde2-6d76eeb0e3f4.png)

**Comment by renepanke** [comment]
HALP!1!!!!1!!!!!!

**Comment by crisstels** [comment]
![image](https://user-images.githubusercontent.com/55994346/136350678-52184446-eb59-4f83-8045-c526a0e68bd2.png)

**Comment by renepanke** [comment]
XD
